- hosts: all
  tasks:
   - name: install haproxy
     yum:
      name: haproxy
      state: present

   - name: Copy HAProxy config
     template:
      src=/home/testme/haproxy.cfg
      dest=/etc/haproxy/haproxy.cfg
      backup=yes
   
   - name: Executing a Command Using Shell Module
     shell: sudo /home/testme/chgip
